### ISSUE TITLE
Support for Verisure integration with Yale doorman

### ISSUE THREAD

**Issue by pohomey** [Charlie-Root/homey-nl-verisure#10]
Would be nice to have support for Verisure integration for Yale doorman.

https://mypages.verisure.com/se/webshop.html#product/1190 
https://mypages.verisure.com/se/webshop.html#product/445
https://www.yale.se/sv/yale/yalese/yale-doorman/styr-ditt-las-med-en-app/

**Comment by Charlie-Root** [comment]
They do not sell this in the Netherlands. If you can provide me with an account i might be able to integrate it..

**Comment by jampeef** [comment]
You need access to a lock with it integrated? You could play with my backdoor lock if you want.

Heres someone that has done a python version with lockstatus and lock unlock. 
https://github.com/persandstrom/python-verisure/blob/master/README.md

**Comment by jampeef** [comment]
Charlie-Root Did you check your homey forum messages?

**Comment by Charlie-Root** [comment]
Yes, i will proceed with the lock within a few days.

**Comment by jampeef** [comment]
opening closing is wanted yes.

**Comment by Charlie-Root** [comment]
Well @jampeef when are you home so i can lock/unlock your door? :)

**Comment by jampeef** [comment]
@Charlie-Root  just open it whenever. im home in a hour. but i dont need to be for you to open. its set to autolock now but i can change that if you want

**Comment by Charlie-Root** [comment]
I first need confirmation that the doorlock code and alarmcode are the same. Then i will proceed.

**Comment by jampeef** [comment]
i dont have the alarm only the locks. so nothing unexpected can happen

**Comment by Charlie-Root** [comment]
Can you show me a screenshot of your user configuration in mypages to see if the alarm code and lock code are the same ?

**Comment by jampeef** [comment]
i dont have the alarm so no. but each person has their own code. and i think you select if lock/unlock will arm/disarm.

**Comment by Charlie-Root** [comment]
I will assume that the alarm code and door code are the same for this version then. I will add the functionality in an hour or so.

**Comment by jampeef** [comment]
@Charlie-Root sounds brilliant

**Comment by Charlie-Root** [comment]
Done. Added support in version 1.0.7
