### ISSUE TITLE
Newest version verisure

### ISSUE THREAD

**Issue by Merlinuf** [Charlie-Root/homey-nl-verisure#11]
Hi,

Can you please make it work with latest version of Verisure hardware and yale doorman

**Comment by Charlie-Root** [comment]
Can you tell me, what does not work?

**Comment by Merlinuf** [comment]
Hi Charlie,

Thanks for your reply,

The driver shows up as null null. The driver is the only one showing, and the rest doesn’t even show, the wheel is only spinning can’t add fire alarms or door sensors. If I try to arm/disarm I get a timeout error.

I have the latest version of there system


Med vänlig hälsning,

Kristoffer Persson

**Comment by Merlinuf** [comment]
Okay,
The whole pairing process aint working for me. It’s only spinning and then times out.
Tried just now and it’s been several hours since I installed the plugin


Med vänlig hälsning,

Kristoffer Persson

> 14 juni 2018 kl. 11:25 skrev Charlie <notifications@github.com>:
> 
> In the next version i will add more logging.
> 
> I have seen some examples where it took 15 minutes or more for the API to
> finally show data in Homey. Only 1-2 instances where it really didn't work.
> 
> Kind regards,
> Wieger
> 
> 
>

**Comment by Merlinuf** [comment]
Okay,
Yes i live in sweden so, but that should work hoppfully you can fix it


Med vänlig hälsning,

Kristoffer Persson

**Comment by Charlie-Root** [comment]
Solved in version 1.0.6.

i will look at the lock asap.

**Comment by Merlinuf** [comment]
Great thanks, when do that version come out in the homey AppStore?


Med vänlig hälsning,

Kristoffer Persson

**Comment by Charlie-Root** [comment]
It was published a few hours ago

Op zo 17 jun. 2018 17:53 schreef Merlinuf <notifications@github.com>:

**Comment by Merlinuf** [comment]
Nice its been added now, but gets an error when arming the alarm, but it actually arms in the Verisure app but gets a timeout error in the app. 

Would love the locks next, great work and fast bug fixing


Med vänlig hälsning,

Kristoffer Persson

**Comment by Charlie-Root** [comment]
You are using the BETA app of homey i guess. i see. it's a typo. it works but the app says it failed.

I will correct that. Locks and Smartplugs are next, together with the camera's. But expect that in a few weeks as i do not do this as my fulltime job and i have holidays soon :)

**Comment by Charlie-Root** [comment]
Bugs all fixed. Lock is a duplicate.

**Comment by Merlinuf** [comment]
@charlie-root it cant find the new speaker unit, the one Verisure uses to talk to you. This van Also give you temp
