### ISSUE TITLE
Flow not triggered

### ISSUE THREAD

**Issue by BusterKrabba** [Charlie-Root/homey-nl-verisure#12]
All of a sudden my flow is not triggered by "the state changed". The flow starts however by testing the flow

**Comment by Phearz** [comment]
Great !

**Comment by BusterKrabba** [comment]
in my case it was alarm state....but following your action on the none responsive  API servers of verisure i will test again

**Comment by Charlie-Root** [comment]
@BusterKrabba @Phearz 
Well i believe it is not updating anything right now. I was using e-api01 as host, that throws this error:

> _<response><status><errorGroup>SERVICE_UNAVAILABLE</errorGroup><errorCode>SYS_00004</errorCode><errorMessage>XBN Database is not activated</errorMessage></status></response>

I just uploaded version 1.0.6 and added support for multiple API hosts. Should work flawless with that version.

**Comment by BusterKrabba** [comment]
where is the new version  1.0.6 to be found ? It is not yet visible in Homey App store (yet)

**Comment by Charlie-Root** [comment]
Athom has to review and approve each update.. takes 2 days or so.. 

You can just grab the github version and use developer tools to manually install it

**Comment by BusterKrabba** [comment]
Thanks for impressive fast responses !

**Comment by Charlie-Root** [comment]
NP, and a donation is welcome (if everything works) ;-)

**Comment by Phearz** [comment]
sent a small one its at least something

**Comment by Charlie-Root** [comment]
Update has been published. Can you confirm it works now ?

**Comment by BusterKrabba** [comment]
Works fine again Donation sent. Thanks!

**Comment by Charlie-Root** [comment]
Thanks for confirming (and the donation :-) )
