### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by Merlinuf** [Charlie-Root/homey-nl-verisure#13]
Hi,
When i activate alarm or unlock a door in the app I get an timeout 5000ms but it works, still annoying that I get a timeout, why is that?

**Comment by Merlinuf** [comment]
Hi 
Yes in the app 


Med vänlig hälsning,

Kristoffer Persson

**Comment by Merlinuf** [comment]
Hi Charlie,

I noticed one device not showing up it’s the climat sensor. Can you add that aswell?


Med vänlig hälsning,

Kristoffer Persson

**Comment by Charlie-Root** [comment]
I do not get any timeout here.. thats weird. 

What climat sensor do you have?

**Comment by Merlinuf** [comment]
Hmm,
Just notice it doesn’t seem to save my login details on the app settings. I need to login every time with mail avccount to Verisure. Maybe that’s a problem?


Med vänlig hälsning,

Kristoffer Persson

**Comment by Charlie-Root** [comment]
That sounds weird.

Can you remove the app, restart homey and reinstall? I did not hear of this
issue before.

Kind regards,
Wieger

**Comment by Merlinuf** [comment]
Some problem after uninstall and restart and then install


Med vänlig hälsning,

Kristoffer Persson

> 27 juni 2018 kl. 12:42 skrev Charlie <notifications@github.com>:
> 
> That sounds weird.
> 
> Can you remove the app, restart homey and reinstall? I did not hear of this
> issue before.
> 
> Kind regards,
> Wieger
>

**Comment by Charlie-Root** [comment]
The app also does not work anymore. I think they have more issues

Op wo 27 jun. 2018 18:05 schreef Merlinuf <notifications@github.com>:

**Comment by Merlinuf** [comment]
Who? Verisure or homey?


Med vänlig hälsning,

Kristoffer Persson

**Comment by Charlie-Root** [comment]
The verisure app on my phone also doesn't work anymore

Op wo 27 jun. 2018 18:11 schreef Merlinuf <notifications@github.com>:

**Comment by Merlinuf** [comment]
Yea i saw that now, maybe tjats the problem


Med vänlig hälsning,

Kristoffer Persson

**Comment by Charlie-Root** [comment]
I am pretty sure. :-)

Op wo 27 jun. 2018 18:17 schreef Merlinuf <notifications@github.com>:

**Comment by Merlinuf** [comment]
Ok i have texted Verisure lets see What they say


Med vänlig hälsning,

Kristoffer Persson

**Comment by Merlinuf** [comment]
Verisure up and running but now your app crashes




Med vänlig hälsning,

Kristoffer Persson

**Comment by Charlie-Root** [comment]
The app is still getting a timeout. I will check asap.

Op wo 27 jun. 2018 18:41 schreef Merlinuf <notifications@github.com>:

**Comment by Charlie-Root** [comment]
Still morning is working.   I will check tomorrow again.  Looks like
verisure is having issues

Op wo 27 jun. 2018 18:41 schreef Merlinuf <notifications@github.com>:

**Comment by Merlinuf** [comment]
Maybe an api problem but just guessing


Med vänlig hälsning,

Kristoffer Persson

**Comment by Charlie-Root** [comment]
They changed their api... I will update it tomorrow

Op wo 27 jun. 2018 22:21 schreef Merlinuf <notifications@github.com>:

**Comment by Charlie-Root** [comment]
Judging by the amounts of bad reviews on Google Play we are not alone. The app is instable, crashes and is not able to login. The Homey app has the same results, timeout after 5000ms. 

Sadly i cannot do much about it right now.. i hope verisure updates the google playstore app soon so i can debug and update the Homey app.

**Comment by Merlinuf** [comment]
The Verisure app had worked perfect for me on My iPhone for several years. So they just have some technical issues at the moment


Med vänlig hälsning,

Kristoffer Persson

**Comment by Charlie-Root** [comment]
Well, funny story. I just found out why Verisure was having so much issues.

The Homey app became more populair generating a lot more traffic for the Verisure API servers. Judging by the email i just saw we took their system down 👍 

I have requested direct contact with them in order to see what we can do about it..

**Comment by Merlinuf** [comment]
Haha thats bad 


Med vänlig hälsning,

Kristoffer Persson

**Comment by Merlinuf** [comment]
I got the mail also from them.
So I think you need to lower the pull from the API to a higher number


Med vänlig hälsning,

Kristoffer Persson

**Comment by Charlie-Root** [comment]
Hi,

I saw. I just have my app up and running again with lower values. i will test it for 24 hours and then push and update.

Kind regards,
Wieger

**Comment by Merlinuf** [comment]
G8 Charlie 


Med vänlig hälsning,

Kristoffer Persson

**Comment by Charlie-Root** [comment]
G8?

Op do 28 jun. 2018 18:41 schreef Merlinuf <notifications@github.com>:

**Comment by Merlinuf** [comment]
Great :)


Med vänlig hälsning,

Kristoffer Persson

**Comment by Charlie-Root** [comment]
The app is working great.  I will send an update out tomorrow

Op do 28 jun. 2018 19:57 schreef Merlinuf <notifications@github.com>:

**Comment by Merlinuf** [comment]
Thank you for all the hade work


Med vänlig hälsning,

Kristoffer Persson

**Comment by Charlie-Root** [comment]
Just pushed the update, pending Athom approval..
