### ISSUE TITLE
Unusual amounts of data traffic

### ISSUE THREAD

**Issue by Tussrix** [Charlie-Root/homey-nl-verisure#14]
Hello. 
I received a mail from Verisure today, see below. I'm only looking at alarm status and door status, why all this communication?

Cut out from email: 

"Dear Customer,
We are seeing  being generated and sent by you, or someone using your credentials, towards our systems. There can be many reasons for this amount of traffic to happen, but in this case we suspect that you are interacting directly with our back-end APIs and systems.  While we really appreciate ingenuity and welcome curious minds to look closer at our alarms, we do not officially support external connections.

We have registered about 50000-150000 requests per 24 hours in the latest week from your account. This far exceeds any normal usage. We strongly advice that you adjust any interactions, supported or not, to an expected level. We reserve the right to take actions, which can include throttling or temporary lock-out, to protect our systems from unstable traffic or interference."

What shall I do?

/Rikard

**Comment by Charlie-Root** [comment]
Hi,

I saw. I just have my app up and running again with lower values. i will test it for 24 hours and then push and update.

Kind regards,
Wieger

**Comment by Charlie-Root** [comment]
Just pushed the update, pending Athom approval..
