### ISSUE TITLE
Status Update fails

### ISSUE THREAD

**Issue by rdoubleu** [Charlie-Root/homey-nl-verisure#15]
After 3 days of smooth running my Homey does not update the status of my Alarm. It still thinks its armed away while I'm home.  Restarting of Homey or de app did not do the trick.

Many thanks.

**Comment by Charlie-Root** [comment]
Yea they blocked it. I am pushing an update right now.

**Comment by Charlie-Root** [comment]
Just pushed the update, pending Athom approval..
