### ISSUE TITLE
New Version

### ISSUE THREAD

**Issue by Merlinuf** [Charlie-Root/homey-nl-verisure#16]
Hi,

The App hasnt been updated, did you version update it ? its still 1.0.7 here aswell.

Regards
Kristoffer

**Comment by Charlie-Root** [comment]
Sorry i did not have any time the past days. i will send out the update
tomorrow.

**Comment by nerdtechse** [comment]
Charlie-Root.. How did it go? Could you please send it out?

**Comment by Charlie-Root** [comment]
I just updated it to 1.0.8 through atom store. Sorry for the delay, lots of work.. 

1.0.8 is a quick fix and working stable for 7 days here. I will implement "better coding" when i have some time to spare.
