### ISSUE TITLE
One door/window sensor does not report status changes

### ISSUE THREAD

**Issue by jasplund** [Charlie-Root/homey-nl-verisure#17]
After upgrading to 1.0.8 status changes are not picked up. The status that the window or door had when upgraded. I had one open window and it is reported as open even though I close it. All the other doors and windows where closed and are still reported as closed when I open them.

**Comment by Merlinuf** [comment]
Same here but in homekit i can see in Verisure app that alarm is armed but not in Homeapp on iphone this worked before

**Comment by BusterKrabba** [comment]
Have the same issue. Furthermore the old problem with alarm stays changes not working in flows is back

**Comment by BusterKrabba** [comment]
mean alarm status changes

**Comment by Charlie-Root** [comment]
Hello,

I am currently on holiday so i cannot do much. I see that Verisure is doing everything they can to block our app, sadly..

I will be back in 2-3 weeks and recode the app so that they cannot block it.

Wieger Bontekoe

**Comment by BusterKrabba** [comment]
Any solution yet with the Verisure blocking?

**Comment by BusterKrabba** [comment]
All of a sudden alarm status changes works in flows!

**Comment by Charlie-Root** [comment]
Just returned from holiday today and see the same!

Met vriendelijke groet,
Wieger Bontekoe

Information Trends B.V.
Apollovlinder 27
1113 LL DIEMEN
tel.: 020-3697635




Op di 14 aug. 2018 19:12 schreef BusterKrabba <notifications@github.com>:

**Comment by Charlie-Root** [comment]
Should be fixed in 1.0.9
