### ISSUE TITLE
Alarm status is not changing at all

### ISSUE THREAD

**Issue by Ogge66** [Charlie-Root/homey-nl-verisure#19]
Since it was "blocked" in version 1.07 nothing changes when arming and disarming the alarm. It still just says armed since over a week ago. I thought 1.08 would solve that...?

**Comment by Charlie-Root** [comment]
Hello,

I am currently on holiday so i cannot do much. I see that Verisure is doing everything they can to block our app, sadly..

I will be back in 2-3 weeks and recode the app so that they cannot block it.

Wieger Bontekoe

**Comment by Charlie-Root** [comment]
Should be fixed in 1.0.9, pending approval at Athom
