### ISSUE TITLE
Login issue - no PostNL account

### ISSUE THREAD

**Issue by pohomey** [Charlie-Root/homey-nl-verisure#2]
It seems (or have i misunderstood the non-English info) that the settings page require a login/email account on PostNL. I don't have any login credentials on PostNL associated with my verisure system. I login using an account on verisure.se.

**Comment by Charlie-Root** [comment]
There is no need for a PostNL account, can you tell me where you see this ? I cannot reproduce that.

**Comment by pohomey** [comment]
Ver 1.5.11
![image](https://user-images.githubusercontent.com/34522719/40899050-17ecb4ee-67c5-11e8-9b7c-81e9ef1921f2.png)

**Comment by Charlie-Root** [comment]
Looks like you are running the first beta version. This has been resolved. You can update the code from GitHub or wait for the update through the App Store. 

To be clear: This was only an issue with the localization file. Entering your username/password will not send those credentials to PostNL but will log you in to the verdure system.

**Comment by pohomey** [comment]
I run v1.0.0 - 31.05.18.

Sure I'll wait on an updated version on app store.

**Comment by Charlie-Root** [comment]
Just released version 1.0.2.
