### ISSUE TITLE
Yale doorman

### ISSUE THREAD

**Issue by Merlinuf** [Charlie-Root/homey-nl-verisure#21]
Locks stopped responding it just gives a timeout 5000ms, this worked before

**Comment by Charlie-Root** [comment]
Hello,

I am currently on holiday so i cannot do much. I see that Verisure is doing everything they can to block our app, sadly..

I will be back in 2-3 weeks and recode the app so that they cannot block it.

Wieger Bontekoe

**Comment by Charlie-Root** [comment]
Should be fixed in 1.0.9, pending approval at Athom
