### ISSUE TITLE
Add Panasonic heatpump to app

### ISSUE THREAD

**Issue by prj84** [Charlie-Root/homey-nl-verisure#22]
I have a panasonic heatpump that is connected to the Verisure system, Is it possible to add that to the app? I will be more than happy to help :-)

![image](https://user-images.githubusercontent.com/35060010/43948424-12b1a822-9c8b-11e8-82cf-48b6a6a02cc9.png)

![image](https://user-images.githubusercontent.com/35060010/43948404-0559afc6-9c8b-11e8-963c-bcf5bd67c078.png)

**Comment by Charlie-Root** [comment]
Sadly they do not sell that in Holland and verisure is not working with us in this case....

If you can provide XML output of the API, i can get it to work

**Comment by prj84** [comment]
Is this something accessible from the verisure site?  From my loggin page?  The console in Chrome?

**Comment by Charlie-Root** [comment]
Can you provide me with the exact type of Panasonic Heatpump ?

Also you can create a read-only account within Mypages so i can check

**Comment by Charlie-Root** [comment]
no response, closing

**Comment by prj84** [comment]
Sorry, I have not seen this! I can make a read only account tomorrow :-) I think all heatpunps through verisure interface has the same interface :-) Where should I send username/password?

Mvh

Pål Raymond Johansen

**Comment by prj84** [comment]
Sorry, I have not seen this! I can make a read only account tomorrow :-) I think all heatpunps through verisure interface has the same interface :-) Where should I send username/password?

**Comment by Charlie-Root** [comment]
Please send them by email:
wieger _ AT _ skynet-ict.nl

**Comment by oyjohan** [comment]
Hello. Is there any progress on this matter?

**Comment by follox** [comment]
I also have the Panasonic heatpump and would love to contribute in order to get this . Anything I can do?
