### ISSUE TITLE
Invalid e-mail...

### ISSUE THREAD

**Issue by JohanLagergren** [Charlie-Root/homey-nl-verisure#25]
<img width="669" alt="skarmavbild 2018-08-26 kl 07 32 43" src="https://user-images.githubusercontent.com/42699148/44625169-f463a580-a902-11e8-96e2-823766b9c02c.png">

Latest Homey update. The response comes suspiciously fast, like it doesn't even run it against Verisure. Tried to uninstall and reinstall as well as reboot Homey.

**Comment by oscst071** [comment]
I have the same issue.

**Comment by runnane** [comment]
This seems to be related to the following line:
`lib/Api.js:                     this._BASE_HOST = 'e-api01.verisure.com';`
Changing this to 'e-api02.verisure.com' solved the issue for me.

**Comment by JohanLagergren** [comment]
Good! But where can i reach that piece of code within Athom Homey?

(New to the Homey, had RPi before)

/Johan 

Skickat från min iPhone

**Comment by runnane** [comment]
I am somewhat new to Homey myself, but I do not think you can edit apps once they are deployed to the Homey. This means you might have to compile and deploy the updated package yourself. 
I cloned the repo, and used the athom cli to install an updated version of the code onto the Homey.

Check the athom homey developer guides, or the athom cli page at https://www.npmjs.com/package/athom-cli

Something like this may do the trick
```
git clone https://github.com/Charlie-Root/homey-nl-verisure
cd homey-nl-verisure
# update lib/Api.js
athom login
athom app install
```

**Comment by oscst071** [comment]
Charlie-Root, any info about when the version 1.2.0 is out?

Thx! And great job!

**Comment by Charlie-Root** [comment]
Version update has been out, should be solved.
