### ISSUE TITLE
Support for Smartplug

### ISSUE THREAD

**Issue by HelgeFH** [Charlie-Root/homey-nl-verisure#28]
Hi,
Have you looked at adding support for the Smartplug, Water sensor and Climat sensor?

Thanks
Helge

**Comment by Charlie-Root** [comment]
Sadly they do not sell that in the Netherlands so i have no way of testing that myself.

**Comment by HelgeFH** [comment]
Send me your address and I will ship you one. I have a couple not used.

Sent from my mobile device...

Med vänlig hälsning/Regards
Helge Fabricius-Hansen
Mobile: 0733-144636 (+46 733 144 636)

14 sep. 2018 kl. 14:38 skrev Charlie <notifications@github.com<mailto:notifications@github.com>>:


Sadly they do not sell that in the Netherlands so i have no way of testing that myself.

**Comment by Charlie-Root** [comment]
There is no option to send private messages on Github.. sadly

**Comment by Charlie-Root** [comment]
What you can do, create a new read-only account for your system and send me the credentials through athom forum (prive message)

**Comment by Charlie-Root** [comment]
no response, closing

**Comment by HelgeFH** [comment]
Happy to send a smart plug. Just need an address... :-)

Sent from my mobile device...

Med vänlig hälsning/Regards
Helge Fabricius-Hansen

On 28 Jan 2019, at 10:30, bjdyke <notifications@github.com<mailto:notifications@github.com>> wrote:


I'd like this resurrected! In Sweden very Verisure supply smart plugs and it would be great to control them in Homey. The guy above listed his mobile number. Can't you sms him your address and get this going. Thanks for the app by the way and keep up the good work!

**Comment by bjdyke** [comment]
Yes! I was hoping to encourage the developer to text you his address as your mobile number is in an earlier post!

**Comment by Othemars** [comment]
I have a couple of Smart plugs too.
It would be nice to be able to use them.
