### ISSUE TITLE
Contact devices only react when alarm is triggered

### ISSUE THREAD

**Issue by Phearz** [Charlie-Root/homey-nl-verisure#3]
I don't know how the API works or enables but a feature that would be nice if the contact alarm could be used in other flows when the alarm is not triggered. i.e. log each time the from door is open.

![bild](https://user-images.githubusercontent.com/4085813/41035546-43e8f084-698d-11e8-8807-683787c896be.png)

You have given so much already Im so happy thanks for being awesome

**Comment by Charlie-Root** [comment]
![image](https://user-images.githubusercontent.com/8972988/41035922-877ec7c8-698e-11e8-962f-1dceb84da4b3.png)
I am not sure what you mean, i already use flows that monitor if the window is open/closed in combination with rain and/or time.

**Comment by Phearz** [comment]
Then is possibly a bug then the flow is not triggered when I open the doors. Tonight I look into it further, is there any log entry I can provide to you ? 

![bild](https://user-images.githubusercontent.com/4085813/41036096-373ffd4e-698f-11e8-9dd9-a2e33c5abc11.png)

**Comment by Charlie-Root** [comment]
When a door is closed the contact alarm is **on**. When you open the door, the contact alarm is **off**

Maybe not very logical....

**Comment by Charlie-Root** [comment]
Just tested it on version 1.0.2 and works. i receive the push notification within 30 seconds.

**Comment by Phearz** [comment]
Sorry the feature needs to be enabled in verisure first once I did that it worked just fine. Its awesome <3 I continue testing
