### ISSUE TITLE
No status updates anymore?

### ISSUE THREAD

**Issue by Ogge66** [Charlie-Root/homey-nl-verisure#32]
I’m not getting any status changes since 2 days ago. Known issue?

**Comment by Merlinuf** [comment]
Same here


Med vänlig hälsning,

Kristoffer

**Comment by Charlie-Root** [comment]
I see the same since this morning. i will look in to it.

**Comment by Charlie-Root** [comment]
Anybody also having issues with the mobile app ? Doesn't work here either.

**Comment by Ogge66** [comment]
Yes
Reported to Verisure so probably some major fuckup somewhere :D

**Comment by Merlinuf** [comment]
Me too yesterday had to change password after that I could logon to app again.


Med vänlig hälsning,

Kristoffer

> 20 sep. 2018 kl. 10:12 skrev Ogge66 <notifications@github.com>:
> 
> Yes
> Reported to Verisure so probably some major fuckup somewhere :D
> 
> Sent from my iPhone
>

**Comment by Merlinuf** [comment]
Verisure just gave me the answer, they are blocking access if anything tries to get status more then once every half an hour

And the homey app (Verisure) fetches every 5 minutes I think


Med vänlig hälsning,

Kristoffer

> 20 sep. 2018 kl. 10:12 skrev Ogge66 <notifications@github.com>:
> 
> Yes
> Reported to Verisure so probably some major fuckup somewhere :D
> 
> Sent from my iPhone
>

**Comment by Ogge66** [comment]
So what do we do...?

**Comment by Merlinuf** [comment]
Hopefully Charlie will do what he can


Med vänlig hälsning,

Kristoffer

> 21 sep. 2018 kl. 15:59 skrev Ogge66 <notifications@github.com>:
> 
> So what do we do...?
> 
> Sent from my iPhone
>

**Comment by Ogge66** [comment]
I’ve understood that homeseer and indigo are “constantly” logged in and have never triggered these warnings so that might be worth looking in to?

**Comment by Charlie-Root** [comment]
I do the same (i re-use the cookie with all requests). So that should not be an issue.. I just tried with polling time of 5 minutes and they still block it.

But i do have an idea.. let me look in to it this weekend.

**Comment by Ogge66** [comment]
Thank you very much!

**Comment by Merlinuf** [comment]
Thanks C
And thanks for all your work


Med vänlig hälsning,

Kristoffer

**Comment by oscst071** [comment]
Same problem here. Neither Verisure app or Verisure Homey app works. 

I hope you can solve this C ;) 

Great job!

**Comment by Ogge66** [comment]
Copied from Swedish verisure support

"Hej! 

Ditt konto skickar för många förfrågningar till vårt system och kontot blir därav låst temporärt. 
Troliga skäl till detta är att man använder någon typ av hemautomatation, till exempel Homey eller Homeassistant. 
För att avhjälpa detta problem behöver du justera antalet förfrågningar programmet gör till oss. Vår acceptans ligger på en förfrågan per halvtimme. 

När detta är justerat släpper spärren inom några timmar.
"

**Comment by prj84** [comment]
SmartThing Verisure integration checks once a minute. If it can not connect it waits for 5 minuttes, then if it still can not connect i waits for 10 minuttes. Then it is allways connects. Every 30 sec is to much I’m affraid. Maybe add a option to settings to set this by user?

**Comment by Charlie-Root** [comment]
> SmartThing Verisure integration checks once a minute. If it can not connect it waits for 5 minuttes, then if it still can not connect i waits for 10 minuttes. Then it is allways connects. Every 30 sec is to much I’m affraid. Maybe add a option to settings to set this by user?

I am currently rewriting the entire api with this idea in mind. Thanks for that! Takes a bit of time, hope to be done by this weekend.

**Comment by Charlie-Root** [comment]
i just pushed version 2.0.0. Please let me know if this resolves the issues.

**Comment by oscst071** [comment]
I may be stupid, but how do I update? I have choose to automatically update the app, but nothing happens. What do I need to do? Sorry :)

**Comment by oscst071** [comment]
I may be stupid, but how do I update? I have choose to automatically update the app, but nothing happens. What do I need to do? Sorry :)

**Comment by Charlie-Root** [comment]
> I may be stupid, but how do I update? I have choose to automatically update the app, but nothing happens. What do I need to do? Sorry :)

will go by itself as soon as Athom approves the update.

**Comment by Ogge66** [comment]
Update hasn’t been pushed out by Sthlm yet :)

**Comment by Charlie-Root** [comment]
That will go by itself as soon as Athom approves my update

**Comment by Charlie-Root** [comment]
in version 2.0.0 the update interval is 60 seconds as that seems to work
for now. Arming or Disarming the alarm is possible using flows, if that
doesn't work please open a new issue.

**Comment by Sagittarius-dk** [comment]
Why not make the interval an input felt, like others do 😉

**Comment by Charlie-Root** [comment]
Version 2.0.2. released that should solve it. If not feel free to open a new issue.
