### ISSUE TITLE
App still crashes when adding smoke detectors

### ISSUE THREAD

**Issue by prj84** [Charlie-Root/homey-nl-verisure#36]
App crashes as soon smoke detectors is added. Ass soon as they are removed and app restarts it works fine again.

Same issue for other users in Norway

The unique log ID is: d4ed3106-4aed-456c-8b35-64823f57a725

**Comment by BusterKrabba** [comment]
For me, the app crashes constantly

**Comment by janbsson** [comment]
Crashes immediately for me too.

**Comment by Charlie-Root** [comment]
Please test again in 2.0.2

**Comment by Charlie-Root** [comment]
no response. assume solved.

**Comment by prj84** [comment]
Still crashes on 2.0.2
