### ISSUE TITLE
v 2.0.0 crashed

### ISSUE THREAD

**Issue by oscst071** [Charlie-Root/homey-nl-verisure#37]
Version 2.0.0 crashes directly after download. Guess that everyone have this issue.

**Comment by Wanegn** [comment]
Looks like it is failing due to the smoke detectors.

**Comment by fredrikjohnsson** [comment]
Same issue here, crashes immediately after adding a device. Also tried to re-install without any success.

**Comment by Sagittarius-dk** [comment]
same here

**Comment by BusterKrabba** [comment]
Charlie, we are all awaiting your comments!

**Comment by Charlie-Root** [comment]
Solved in version 2.0.2.

**Comment by Wanegn** [comment]
Works great now, updated and activated it yesterday no issues so far !

**Comment by Charlie-Root** [comment]
Thanks, glad to hear!

**Comment by oscst071** [comment]
So far it's working great! Nice job C
