### ISSUE TITLE
Yale smartlock

### ISSUE THREAD

**Issue by Merlinuf** [Charlie-Root/homey-nl-verisure#39]
Now it wont open says timeout 5000ms

**Comment by Charlie-Root** [comment]
Everything else in the APP is working? i did not make changes to the lock

**Comment by Merlinuf** [comment]
Its the same error as before timeout 



Med vänlig hälsning,

Kristoffer

**Comment by Charlie-Root** [comment]
> Its the same error as before timeout Med vänlig hälsning, Kristoffer
> […](#)
> 5 nov. 2018 kl. 17:01 skrev Charlie ***@***.***>: Everything else in the APP is working? i did not make changes to the lock — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

But, as i asked, is everything else (alarm and stuff) working as expected?

**Comment by Charlie-Root** [comment]
> Now it wont open says timeout 5000ms

I have tested and I assume you are using the new beta app. The error you get is something I get a lot, seems a bug in the latests firmware.. I have that too with lights and other sensors.
