### ISSUE TITLE
Smoke alarm - always crashes

### ISSUE THREAD

**Issue by hakan-b** [Charlie-Root/homey-nl-verisure#41]
I would love this to work, but have tried to use the smoke detectors as device for temp. It works 10 minutes or so, then crashes. tried  several of the apps versions  for several month but it still crashes. Seen other users  comments with problems with smoke detectors. Is this a general problem?? Is the problem on my side??? Would love to get it to work

**Comment by Charlie-Root** [comment]
When it crashes, send the crash report. So far did not see any.

**Comment by Merlinuf** [comment]
Hi,

Are your Verisure system up to date?
I have no problems except for my locks 
And I fixed that with another app


Med vänlig hälsning,

Kristoffer

**Comment by hakan-b** [comment]
Only today 4 crash reports have been sent from my Homey app on my computer. Or do you mean that I should manually get them and send you?? If so, how do I do that

///Håkan

**Comment by hakan-b** [comment]
Here is a screenshot showing that 3 of many crash reports have been sent.

Do not know hoe to manually pull them out to send to you

///Håkan

**Comment by Charlie-Root** [comment]
I just checked, didn't receive any crash report. What version of the app are you on?

**Comment by Merlinuf** [comment]
Your alarm system did you do a system uppdate from the Verisure app?


Med vänlig hälsning,

Kristoffer
