### ISSUE TITLE
State chance in flows 2.0

### ISSUE THREAD

**Issue by burnis** [Charlie-Root/homey-nl-verisure#44]
I've updated to the test release of Homey (2.0).
I can read the state of the system but it does not work to use the state in a flow.

**Comment by prj84** [comment]
I can verify the same problem

**Comment by nr8Design** [comment]
I have the same issue

**Comment by prj84** [comment]
This seems to be a Homey v2 firmware issue. This is related to many devices as well

**Comment by prj84** [comment]
They say that the issues is fixed, but it is still the same issue here eith state change

**Comment by Charlie-Root** [comment]
I have this issue with all apps, including KAKU and Verisure. So i do not
believe they fixed this issue.

**Comment by oscst071** [comment]
Any thing new in this? Still not work to trigger a flow with state change?

**Comment by Hihaj** [comment]
Same here. Have the latest Homey firmware. Tried reinstalling the Verisure app and now it doesn’t seem to even find any devices, just times out.

**Comment by Charlie-Root** [comment]
Should be solved in the latest homey update.
