### ISSUE TITLE
Unable to trigger a flow when alarm state change

### ISSUE THREAD

**Issue by oscst071** [Charlie-Root/homey-nl-verisure#46]
Hi! 

I have updated to firmware 2.0 and everything works fine besides to trigger a flow (when column) with a alarm state change. For example all my lights used to turns off when I leave and sets the alarm to armed.

**Comment by janbsson** [comment]
Me too

**Comment by tommyherman** [comment]
Exactly the same issue for me.

**Comment by janbsson** [comment]
As a workaround i use a timer that checks the alarm state and starts the action if the alarm state changes (using logic variable for prev state which is also updated when action occurs ). This works since the alarm state is updated but it just don’t can be used to trigger.

**Comment by Charlie-Root** [comment]
This was a bug in Homey itself, should be fixed now. is working for me.

**Comment by BusterKrabba** [comment]
Just tested. Works fine for me too
