### ISSUE TITLE
Future improvment: Add camera/motion detectors

### ISSUE THREAD

**Issue by Phearz** [Charlie-Root/homey-nl-verisure#6]
I would love to have my "old"(previous generation) camera /motion detectors the homey as well with verisure app.

I have tried fiqure out the model number for my current with no success. Here is a picture of my current kamera sensor. 
![photo_2018-06-10_13-39-11](https://user-images.githubusercontent.com/4085813/41201197-af6739aa-6cb3-11e8-877c-72d3ac7c147f.jpg)

I will try this asap its released

**Comment by Charlie-Root** [comment]
As far as i can see these have no metric that can be used with Homey.
